# Generated by Django 5.0.7 on 2024-09-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smallFarm", "0002_soilsample_moisturesensor"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GasAreaSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gasArea_samples",
                        to="teams.team",
                    ),
                ),
            ],
        ),

    ]
