# Generated by Django 5.0.7 on 2024-09-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smallFarm", "0003_gasareasample_gascensor"),
    ]

    operations = [
        migrations.CreateModel(
            name="GasSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gasValue", models.FloatField(blank=True, null=True)),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gasArea_sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gas_sensors",
                        to="smallFarm.gasareasample",
                    ),
                ),
            ],
        ),
    ]
